#! /bin/sh
mount |
grep -v '(.*soft.*)' |
grep -v '(.*bind.*)' |
egrep -v '^sunrpc' |
grep -v 'type tmpfs' |
grep -v 'type devtmpfs' |
grep -v 'type autofs' |
grep -v 'type binfmt_misc' |
LC_ALL=C sort
