#! /bin/sh
mkdir -p ~/.yggdrasil/tmp
touch ~/.yggdrasil/tmp/service_status.last
for TRY in `seq 1 5`; do
  if [ $TRY != 1 ]; then
    sleep 3
  fi
  LAST=`cat ~/.yggdrasil/tmp/service_status.last`
  (env -i /sbin/service --status-all & wait ) 2> /dev/null |
    grep -v '^sendmail' |
    grep -v '^/' |
    grep -v '^recursive clients:' |
    grep -v ' LOG_DROP   all ' |
    grep -v 'Active: ' |
    grep -v 'Starting Jenkins \[  OK  \]' |
    sed 's/Process: [0-9]* /Process: X /' |
    sed 's/└─[0-9]* /└─X /' |
    sed 's/^... .. ..:..:.. /XXX XX XX:XX:XX /' |
    sed 's/\[[0-9]*\]/\[X\]/' |
    sed 's/^.....ACCEPT     /     ACCEPT     /' |
    sed 's/LOG_DROP (.*)/LOG_DROP ()/' |
    sed 's/\[pid[^]]*\]/\[pid\]/' |
    sed 's/(PID[^)]*)/(PID)/' |
    sed 's/(pid[^)]*)/(pid)/' > ~/.yggdrasil/tmp/service_status.last
  echo >> ~/.yggdrasil/tmp/service_status.last
  systemctl list-units --type=service >> ~/.yggdrasil/tmp/service_status.last
  RES=`cat ~/.yggdrasil/tmp/service_status.last`
  if [ "$LAST" == "$RES" ]; then
    echo "$RES"
    exit
  fi
done
echo 'RETRY OVER'
